---
title: "Introductory Mathematics for Economists with Matlab"
author: "Priuz Saboury and Fan Wang"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Introductory Mathematics for Economists with Matlab"
output:
  pdf_document:
    toc: true
    toc_depth: 5
    pandoc_args: '_output_kniti_pdf.yaml'
    includes:
      in_header: 'preamble_book.tex'
  html_document:
    pandoc_args: '_output_kniti_html.yaml'
always_allow_html: true
github-repo: math4econ/math4econ.github.io
---

```{r global_options, include = FALSE}
source(".Rprofile")
```

# Preface {-}

`r text_top_count`

This is a work-in-progress [course website](http://math4econ.github.io/) for Mathematics for Economists, an upper-level undergraduate economics course offered by [Piruz Saboury](https://piruzsaboury.weebly.com/) and [Fan Wang](https://fanwangecon.github.io/). The course covers a subset of topics from *Mathematics for Economists* [@simonblume1994]. Applications focus on households' optimal borrowing and savings problems and firms' optimal inputs problems. Matlab is used throughout.

> [**bookdown site**](https://Math4Econ.github.io/bookdown) and [**bookdown pdf**](https://Math4econ.github.io/bookdown/Introductory-Mathematics-for-Economists-with-Matlab.pdf).

Materials are written in [matlab](https://www.mathworks.com/products/matlab.html) [@matlab] livescript files and shown as HTML files. For HTML files, click on the links below. The livescript files can be downloaded and modified inside matlab. Files are from the [Math4Econ](https://github.com/Math4Econ/Math4Econ.github.io) repository. 

Please contact [Piruz Saboury](https://piruzsaboury.weebly.com/) or [Fan Wang](https://fanwangecon.github.io/) for issues or problems.

From other repositories: for research support toolboxes, see [matlab toolbox](https://fanwangecon.github.io/mecontools/), [r toolbox](https://fanwangecon.github.io/recontools/), and [python toolbox](https://pyfan.readthedocs.io/en/latest/); for code examples, see [matlab examples](https://fanwangecon.github.io/m4econ/), [stata examples](https://fanwangecon.github.io/stata4econ/), [r examples](https://fanwangecon.github.io/r4econ/), [python examples](https://fanwangecon.github.io/py4econ/), and [latex examples](https://fanwangecon.github.io/tex4econ/); for packaging example, see [pkgtestr](http://fanwangecon.github.io/pkgtestr) for developing r packages; for teaching, also see [intro statistics for undergraduates](https://fanwangecon.github.io/stat4econ/).

The site is built using [Bookdown](https://bookdown.org/) [@R-bookdown].

`r text_end_count`
